version: '3.8'

services:
  postgres_dc:
    ports:
      - "5432:5432"
    networks:
      - my_net_1

  backend:
    networks:
      - my_net_1

  nginx_dc:
    ports:
      - "80:80"
    networks:
      - my_net_1


  elastic_dc:
    ports:
      - "9200:9200"
    networks:
      - my_net_1


  etl_dc:
    networks:
      - my_net_1


networks:
  my_net_1:
    driver: bridge
